name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.9.0  # Updated to the latest version as of now
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

- name: Setup Node.js
  uses: actions/setup-node@v2
  with:
    node-version: '14'  # or any other version

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # The Docker context is the root of the repository
        push: true
        tags: manfromdownunder/docker-minecraft-rad2:1.7, manfromdownunder/docker-minecraft-rad2:latest, username/repository:${{ github.sha }}  # Replace with your Docker Hub username, repository name, and tag
        platforms: linux/amd64,linux/arm64,linux/arm/v7  # Add more platforms if needed
