name: Code Scanning and Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  code-scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: "java, dockerfile, shell"  # Scan Java, Dockerfile, and Shell files

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  build-and-push:
    needs: code-scanning  # Only proceed if code-scanning passes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Determine architecture
      run: echo "ARCH=$(echo ${{ matrix.platform }} | cut -d/ -f2)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: manfromdownunder/docker-minecraft-rad2:1.7, manfromdownunder/docker-minecraft-rad2:latest, manfromdownunder/docker-minecraft-rad2:${{ github.sha }}
        platforms: ${{ matrix.platform }}
        build-args: ARCH=${{ env.ARCH }}
