name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]  # Add more platforms if needed
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Determine architecture
      run: echo "ARCH=$(echo ${{ matrix.platform }} | cut -d/ -f2)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: manfromdownunder/docker-minecraft-rad2:1.7, manfromdownunder/docker-minecraft-rad2:latest, manfromdownunder/docker-minecraft-rad2:${{ github.sha }}
        platforms: ${{ matrix.platform }}
        build-args: ARCH=${{ env.ARCH }}  # Pass architecture as a build argument